<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Access History Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            color: #333;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #ffffff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
        }

        .header h1 {
            font-size: 28px;
            color: #ff6723;
            margin: 0;
        }

        .info {
            margin-bottom: 30px;
            font-size: 16px;
        }

        .info p {
            margin: 5px 0;
        }

        .summary {
            margin-bottom: 30px;
            font-size: 16px;
            font-weight: bold;
            background-color: #e7f3fe;
            padding: 15px;
            border-radius: 8px;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: center;
        }

        .table th {
            background-color: #ff6723;
            color: #ffffff;
            font-size: 16px;
        }

        .table td {
            font-size: 14px;
        }

        .table tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .footer {
            text-align: center;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1>Access History Report</h1>
        </div>

        <div class="info">
            <p><strong>Employee ID:</strong> {{ $employee->employee_id }}</p>
            <p><strong>Name:</strong> {{ $employee->name }} {{ $employee->last_name }}</p>
            <p><strong>Department:</strong> {{ $employee->department ?? 'N/A' }}</p>
            <p><strong>Has access</strong>
                {!! $employee->has_access ? ' Yes' : ' No' !!}</p>
        </div>

        <div class="summary">
            <small>Total Access Attempts: {{ $totalAttempts }}</small><br />
            <small>Successful: {{ $successfulAttempts }}</small><br />
            <small>Denied: {{ $deniedAttempts }}</small>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>IP Address</th>
                    <th>Access Result</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($accessAttempts as $attempt)
                    <tr>
                        <td>{{ $attempt->attempted_at }}</td>
                        <td>{{ $attempt->ip }}</td>
                        <td>{{ $attempt->was_successful ? 'Successful' : 'Denied' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <p>Generated by the Access Management System</p>
        </div>
    </div>
</body>

</html>
